# Generated by Django 4.1.1 on 2022-11-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Replacer', '0002_remove_replacefield_standart_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replacer.template', verbose_name='Id шаблона'),
        ),
    ]
