# Generated by Django 4.1.1 on 2022-11-28 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Replacer', '0004_replacefield_owner_template_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacefield',
            name='owner',
        ),
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
