# Generated by Django 4.1.1 on 2022-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Replacer', '0006_replacefield_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacefield',
            name='replace_value',
            field=models.TextField(blank=True, verbose_name='Значение'),
        ),
    ]
