# Generated by Django 4.1.1 on 2022-11-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Replacer', '0008_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_add',
            new_name='customer_abb',
        ),
    ]
