# Generated by Django 4.1.1 on 2022-11-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Replacer', '0009_rename_customer_add_customer_customer_abb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.TextField(blank=True, verbose_name='Текст заказчика для замены'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_abb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сокращение ОВУ'),
        ),
    ]
