# Generated by Django 4.1.1 on 2022-11-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Replacer', '0010_alter_customer_customer_alter_customer_customer_abb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_abb', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Компания')),
                ('company_title', models.TextField(blank=True, max_length=255, verbose_name='Компания в шапке')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Инициалы и фамилия руководителя')),
                ('manager_full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя и отчество руководителя')),
                ('company_address', models.TextField(blank=True, max_length=255, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['company_abb'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-pk'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Заказчик'),
        ),
    ]
