- hosts: all
  become: yes 
  become_user: root

  vars:
    host: "192.168.56.102"
    proj_dir: "{{ inventory_dir }}/.."

  tasks:
    - name: Copy all files
      copy:
        src: '{{ proj_dir }}/'
        dest: /var/www/MailTemplate/
        mode: '0777'
        
    # - name: Install all pack for nginx
      # command:
        # chdir=/var/www/nginx_source/ ./install.sh

    # - name: Copy python bin
      # copy:
        # src: '{{ proj_dir }}/python-3.10.8.tar.gz/'
        # dest: /var/www/python-3.10.8.tar.gz
        # mode: '0777'

    # - name: Make dir in opt for python
      # file: path=/opt/python-3.10.8 state=directory

    # - name: Unarchive python
      # unarchive:
        # src: /var/www/python-3.10.8.tar.gz
        # dest: /opt/python-3.10.8/
        # extra_opts: [--strip-components=1]
        # remote_src: yes

    # - name: Delete tar.gz
      # file: path=/var/www/python-3.10.8.tar.gz state=absent

      # - name: Copy project files
      
    # - name: Make execute install.sh
      # ansible.builtin.command:
        # chmod +x /var/www/nginx_source/install.sh
        #
        
    # - name: Debug {{ proj_dir }}
    # debug:
    # msg: Debug {{ proj_dir }}
       
    # - name: Copy src files
      # ansible.builtin.copy:
       # src: '{{ proj_dir }}/src/'
       # dest: /var/www/MailTemplate/
    # 
    # - name: Copy nginx files
      # ansible.builtin.copy:
       # src: '{{ proj_dir }}/nginx_source/'
       # dest: /var/www/nginx_source/
    
