#!/bin/bash
apt-get --ignore-missing install /var/www/nginx_source/cdebconf_0.249astra9_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/coreutils_8.30-3_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/debconf_1.5.71_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/dpkg_1.19.8.astra.se2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/fontconfig-config_2.13.1-2_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/fonts-dejavu-core_2.37-1_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/fonts-liberation_1%3a1.07.4-11+ci202204290853+astra1_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/gcc-8-base_8.3.0-6_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/iproute2_5.10.0-4~bpo10+1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libacl1_2.2.53-4_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libattr1_1%3a2.4.48-4+ci202107131632+astra2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libaudit1_1%3a2.8.5-2ubuntu6+ci202206080012+astra1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libaudit-common_1%3a2.8.5-2ubuntu6+ci202206080012+astra1_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libbpf0_1%3a0.8.0-1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libbsd0_0.9.1-2+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libbz2-1.0_1.0.6-9.2~deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libc6_2.28-10+deb10u1+ci202207192202+astra4_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libcap2_1%3a2.25-2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libcap2-bin_1%3a2.25-2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libcap-ng0_0.7.9-2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libdb5.3_5.3.28+dfsg1-0.9_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libdebian-installer4_0.119_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libelf1_0.176-1.1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libexpat1_2.2.6-2+deb10u4_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libfontconfig1_2.13.1-2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libfreetype6_2.9.1-3+deb10u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libgcc1_1%3a8.3.0-6_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libgcrypt20_1.8.4-5.deb10u1.astra1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libgd3_2.2.5-5.2+ci202206301705+astra1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libgdbm6_1.18.1-4_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libgdbm-compat4_1.18.1-4_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libgeoip1_1.6.12-1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libgpg-error0_1.35-1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libicu63_63.1-6+deb10u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libjbig0_2.1-3.1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libjpeg62-turbo_1%3a1.5.2-2+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/liblua5.1-0_5.1.5-8.1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/liblzma5_5.2.4-1+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libmaxminddb0_1.3.2-1+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libmnl0_1.0.4-2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnewt0.52_0.52.20-8_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-auth-pam_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-cache-purge_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-dav-ext_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-echo_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-fancyindex_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-geoip_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-geoip2_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-headers-more-filter_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-image-filter_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-lua_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-ndk_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-perl_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-subs-filter_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-uploadprogress_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-upstream-fair_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-http-xslt-filter_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-mail_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-nchan_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-stream_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-stream-geoip_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libnginx-mod-stream-geoip2_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libpam0g_1.3.1-5.astra.se7_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libparsec-base3_3.1+ci65_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libparsec-cap3_3.1+ci65_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libpcre3_2%3a8.39-12_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libperl5.28_5.28.1-6+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libpng16-16_1.6.36-6_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libselinux1_2.8-1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libslang2_2.3.2-2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libssl1.1_1.1.1n-0+deb10u3-astra4+ci5_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libstdc++6_8.3.0-6_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libtextwrap1_0.1-14.2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libtiff5_4.1.0+git191117-2~deb10u4_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libuuid1_2.33.1-0.1.astra2se2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libwebp6_0.6.1-2+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libx11-6_2%3a1.7.1-1astra1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libx11-data_2%3a1.7.1-1astra1_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libxau6_1%3a1.0.8-1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libxcb1_1.14-2astra.se11_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libxdmcp6_1%3a1.1.2-3_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libxml2_2.9.4+dfsg1-7+deb10u4_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libxpm4_1%3a3.5.12-1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libxslt1.1_1.1.32-2.2~deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libxtables12_1.8.5-3~bpo10+1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/libzstd1_1.4.8+dfsg-2.1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/lsb-base_10.2019051400+ci202012021351+astra2_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/nginx_1.18.0-6.1+deb11u2_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/nginx-common_1.18.0-6.1+deb11u2_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/nginx-core_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/nginx-extras_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/nginx-full_1.18.0-6.1+deb11u2_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/nginx-light_1.18.0-6.1+deb11u2_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/perl_5.28.1-6+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/perl-base_5.28.1-6+deb10u1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/perl-modules-5.28_5.28.1-6+deb10u1_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/sensible-utils_0.0.12_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/tar_1.34+dfsg-1_amd64.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/ttf-bitstream-vera_1.10-8_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/ucf_3.0038+nmu1_all.deb -y > install_log.sh
apt-get --ignore-missing install /var/www/nginx_source/zlib1g_1%3a1.2.11.dfsg-1+deb10u1_amd64.deb -y > install_log.sh
